server:
  port: 8082
spring:
  application:
    name: order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: test_tx_group # 定义事务组的名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.68.126.147:3306/seata_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.study: debug